In [3]:
# if-else

if True:
    print('True is true')
    
if False:
    print("It ain't true")

True is true


In [4]:
if 4==4: 
    print('hello')

hello


In [8]:
import numpy as np

randnum = np.random.randn()

if randnum > 0:
    print(randnum)

0.39783552683445456


In [9]:
r = np.random.randn()

if r > 0:
    print(str(r) + ' is positive')
    
else:
    print(str(r) + 'is negative')

0.1754078039877734 is positive


In [10]:
caketype = input()

if caketype == 'carrot':
    print('Total yumminess!')
    
elif caketype == 'chocolate':
    print('Not bad')
    
elif caketype == 'fruit':
    print('Healthy?')
    
else:
    print('cake type not detected')

Not bad


In [13]:
# one-line if statements

caketype = 'Carrot'

if caketype[0].lower() == 'c': print('Probably carrot cake')

print('Probably carrot cake') if caketype[0]=='c' else print('Or not.')

Probably carrot cake
Or not.


In [14]:
if 1 < 3 and 4 == 4:
    print('both are true')

both are true


In [53]:
# Exercise 

# create a dot product function
# function checks that both inputs are numpy arrays (hint: isinstance())
# function checks for same length of two input vectors
# returns dot product if pass, useful error message otherwise

def dut_product(a, b):
    # check that both vectors are numpy arrays
    if not (isinstance(a, np.ndarray) and isinstance(b, np.ndarray)):
        raise Exception('Must be numpy array')
        
    # check that both vectors are of the same length
    if not len(a) == len(b):
        raise Exception(('Must be of the same length'))
    
    return sum(a*b)   
    
v = np.array([4, 10, 8])
w = np.array([7, 9, 11])

dut_product(v, w)

206

In [57]:
a = np.array([1, 2, 4])
b = np.array([4, 5, 1])

print(a*b)

[ 4 10  4]


### For loops

In [63]:
for i in range(6):
    print(i)
print(i)

0
1
2
3
4
5
5


In [60]:
for j in range(4, 11):
    print(j, j**2)

4 16
5 25
6 36
7 49
8 64
9 81
10 100


In [67]:
import numpy as np

numbers = np.linspace(3, 17, 22)

for i in range(len(numbers)):
    x = numbers[i]
    print('Iteration ' + str(i) + ' has numbers value of ' + str(x))

Iteration 0 has numbers value of 3.0
Iteration 1 has numbers value of 3.6666666666666665
Iteration 2 has numbers value of 4.333333333333333
Iteration 3 has numbers value of 5.0
Iteration 4 has numbers value of 5.666666666666666
Iteration 5 has numbers value of 6.333333333333333
Iteration 6 has numbers value of 7.0
Iteration 7 has numbers value of 7.666666666666666
Iteration 8 has numbers value of 8.333333333333332
Iteration 9 has numbers value of 9.0
Iteration 10 has numbers value of 9.666666666666666
Iteration 11 has numbers value of 10.333333333333332
Iteration 12 has numbers value of 11.0
Iteration 13 has numbers value of 11.666666666666666
Iteration 14 has numbers value of 12.333333333333332
Iteration 15 has numbers value of 13.0
Iteration 16 has numbers value of 13.666666666666666
Iteration 17 has numbers value of 14.333333333333332
Iteration 18 has numbers value of 15.0
Iteration 19 has numbers value of 15.666666666666666
Iteration 20 has numbers value of 16.333333333333332
Itera

In [69]:
# soft-coding vs hard-coding

# hundreds of line of codes...

for i in range(100): # hard coding
    pass

# soft one
nIteration = 102

for i in range(nIteration):
    pass

In [72]:
# modulus (remainder after division)
10%7

3

In [73]:
for i in range(19):
    if i % 2 == 0:
        print("{0} is an even numbers".format(i))
    else:
        print("{0} is an odd number".format(i))

0 is an even numbers
1 is an odd number
2 is an even numbers
3 is an odd number
4 is an even numbers
5 is an odd number
6 is an even numbers
7 is an odd number
8 is an even numbers
9 is an odd number
10 is an even numbers
11 is an odd number
12 is an even numbers
13 is an odd number
14 is an even numbers
15 is an odd number
16 is an even numbers
17 is an odd number
18 is an even numbers


In [74]:
# Exercise
# Create a function that reports the Fibonacci series for n + 3 numbers

def fibonacci(n):
    # define what happens when input is 0
    if n < 0:
        print('Only positive numbers are allowed')
    elif n == 0:
        return 0
    
    elif n == 1 & n == 2:
        return 1
    
    else:
        return fibonacci(n-1) + fibonacci(n-2)
    
def fib_seq(n):
    v = [0, 1, 1]
    for i in range(n):
        v.append(sum(v[-2:]))
        
    print(v)

fib_seq(8)    




[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


In [76]:
text = 'Hello, My name is MiKE'

for i in text.casefold():
    if i in 'aeiou':
        continue
    print(i)

h
l
l
,
 
m
y
 
n
m
 
s
 
m
k


### While Loops

In [77]:
# while loops 

toggle = True
i = 0

while toggle:
    print(i)
    i += 1
    
    if i == 8:
        toggle = False
    
    

0
1
2
3
4
5
6
7


In [78]:
i = 0
while True:
    print(i)
    i += 1
    
    if i == 9:
        break

0
1
2
3
4
5
6
7
8


In [79]:
i = 0
while i < 8:
    print(i)
    i += 1

0
1
2
3
4
5
6
7


In [ ]:
# for-loop: preferable when you know in advance the number of iterations 
# while-loop: prefer when you don't know in advance the number of iterations

In [83]:
# Exercise: make a Poisson-like counter
from math import exp
# parameter lambda. Positive number (10)
# start at 1, multiply by random number uniform([0,1])
# target number is smaller than exp(-lambda)
# count the number of iteration until target < exp(-lambda)

p_lambda = exp(-10) 
x = 1
i = 0

while True:
    i += 1
    x = x*np.random.uniform([0, 1])
    print(i)
    if x < p_lambda:
        break
    
    

1


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
import numpy as np

def poissonCounter(lam):
    
    # initialize some variables
    counter, cur_val = 0, 1
    target = np.exp(-lam)
    
    # run algorithm
    # cur_val = cur_val * np.random.rand()
    
    while True:
        counter += 1
        cur_val *= np.random.rand()
        if cur_val < target:
            break
    
    # return the result
    return counter

poissonCounter(10)

5

### Initializing variables

In [9]:
# initialization
r = [] 

# structure of the program
for i in range(0, 10):
    c = i**2
    r.append(c)
    
print(r)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [10]:
import numpy as np

r = np.zeros(10)

for i in range(10):
    r[i] = i**2
    
print(r)
type(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


numpy.ndarray

In [11]:
n = 100

r = np.zeros(n)

for i in range(n):
    r[i] = i**2
    
print(r)

[0.000e+00 1.000e+00 4.000e+00 9.000e+00 1.600e+01 2.500e+01 3.600e+01
 4.900e+01 6.400e+01 8.100e+01 1.000e+02 1.210e+02 1.440e+02 1.690e+02
 1.960e+02 2.250e+02 2.560e+02 2.890e+02 3.240e+02 3.610e+02 4.000e+02
 4.410e+02 4.840e+02 5.290e+02 5.760e+02 6.250e+02 6.760e+02 7.290e+02
 7.840e+02 8.410e+02 9.000e+02 9.610e+02 1.024e+03 1.089e+03 1.156e+03
 1.225e+03 1.296e+03 1.369e+03 1.444e+03 1.521e+03 1.600e+03 1.681e+03
 1.764e+03 1.849e+03 1.936e+03 2.025e+03 2.116e+03 2.209e+03 2.304e+03
 2.401e+03 2.500e+03 2.601e+03 2.704e+03 2.809e+03 2.916e+03 3.025e+03
 3.136e+03 3.249e+03 3.364e+03 3.481e+03 3.600e+03 3.721e+03 3.844e+03
 3.969e+03 4.096e+03 4.225e+03 4.356e+03 4.489e+03 4.624e+03 4.761e+03
 4.900e+03 5.041e+03 5.184e+03 5.329e+03 5.476e+03 5.625e+03 5.776e+03
 5.929e+03 6.084e+03 6.241e+03 6.400e+03 6.561e+03 6.724e+03 6.889e+03
 7.056e+03 7.225e+03 7.396e+03 7.569e+03 7.744e+03 7.921e+03 8.100e+03
 8.281e+03 8.464e+03 8.649e+03 8.836e+03 9.025e+03 9.216e+03 9.409e+03
 9.604

In [13]:
n = 10
r = np.full(n, 5.3454)

r

array([5.3454, 5.3454, 5.3454, 5.3454, 5.3454, 5.3454, 5.3454, 5.3454,
       5.3454, 5.3454])

In [17]:
r = []

for i in range(n):
    r.append(i**2)
    
print(r)
type(r)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


list

In [18]:
del r

In [21]:
r = np.array([])

for i in range(n):
    r = np.append(r, i**2)      # append in numpy
    
print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [24]:
r = np.zeros((4, 5), float)
r[1, 2] = 7
r

array([[0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
# Exercise: time all three methods !

# 1) list append
# 2) numpy append
# 3) numpy initialization

import time 

t = [0]*3
N = 1000

# list append 
tic = time.perf_counter()
r = []

for i in range(N):
    r.append(i**2)
t[0] = (time.perf_counter() - tic) * 1000

# numpy append
tic_ = time.perf_counter()
r = np.array([])

for i in range(N):
    r = np.append(r, i**2)
t[1] = (time.perf_counter() - tic) * 1000

# numpy initialization
tic = time.perf_counter()
r = np.zeros(N)

for i in range(N):
    r[i] = i**2
t[2] = (time.perf_counter() - tic)

print(t)


[0.9817059999477351, 23.106577999897127, 0.0010985040003106405]


### Function error checking

In [55]:
# create a function that will input 2 numbers and output their product
def funfun(x, y):
    # check that in puts are numeric
    x_1 = int(x)
    if not isinstance(x_1, (int and float)):
        raise Exception('Input x must be a number')
    z = x_1 * y
    return z

funfun('3', 2)

Exception: Input x must be a number

In [57]:
x = '4'
x.isnumeric()

True

In [58]:
def funfun(x, y):
    # check that if x is float of int
    if not isinstance(x, (int, float)):
        # check if its numeric or not
        if isinstance(x, str) and x.isnumeric():
            x = float(x)
        else:
            raise Exception('x must be numeric')
        
    z = x * y
    return z

funfun('7', 8)


56.0

In [62]:
def lalaland(x, y):
    
    z = 0
    
    try:
        z = x**y
    except:
        print("Couldn't complete the mission")
    
    return z

lalaland(2, 'hi')

Couldn't complete the mission


0

### Multiple input with zip

In [68]:
some_list = [3, 4, 5, 6]
other_list = [1, 3, 4, 5]

z = []
for i in range(len(some_list)):
    z.append(other_list[i]*some_list[i])     # here is a way of calculating dot product
    
sum(z)
    


65

In [71]:
# Group vectors together

for j, i in zip(some_list, other_list):
    print(i*j)

3
12
20
30


In [75]:
z = zip(some_list, other_list)
lz = list(z)

print(lz)

[(3, 1), (4, 3), (5, 4), (6, 5)]


In [79]:
a = [2, 3, 4, 5, 6, 7, 2, 3, 1]
b = ['d', '3', 'f']

for i, j in zip(a,b):       # also remember that zip is not only limited two lists
    print(i, j)

2 d
3 3
4 f


In [81]:
# Exercise

names = ['alpha', 'beta', 'gamma']
values = [10, 20, 40]

dictionary = {}
for i, j in zip(names, values):
    dictionary[i] = j
    
# or 
D = dict(zip(names, values))
print(D)
    
print(dictionary)
    

{'alpha': 10, 'beta': 20, 'gamma': 40}
{'alpha': 10, 'beta': 20, 'gamma': 40}


### Single line loops

In [90]:
import random

if random.randint(1, 10) > 5: print('This is a large number') # one line if-statement

# one line if-else statement
print('This number is small') if random.randint(1, 10) < 5 else print('This is a large number')

This is a large number


In [91]:
for i in range(10):
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [92]:
[print(i**2) for i in range(10)]

0
1
4
9
16
25
36
49
64
81


[None, None, None, None, None, None, None, None, None, None]

In [95]:
# list comprehension

n = [i**2 - i**(1/2) for i in range(10) if i > 5]
n

[33.55051025721682, 46.35424868893541, 61.17157287525381, 78.0]

In [96]:
# Exercise

text = ['Promising', 'Yves', 'that', 'home', 'on', 'Nobb']

for word in text:
    print(word[0])

P
Y
t
h
o
N


In [98]:
[print(word[0]) for word in text];

P
Y
t
h
o
N


In [100]:
# convert range to list 

new_list = [''] * 10

for i in range(10):
    if i % 2 == 1:
        new_list[i] = 'Odd'
    else:
        new_list[i] = i
        
new_list

[0, 'Odd', 2, 'Odd', 4, 'Odd', 6, 'Odd', 8, 'Odd']

In [105]:
new_list = ['Odd' if i%2 == 1 else i for i in range(10)]
new_list


[0, 'Odd', 2, 'Odd', 4, 'Odd', 6, 'Odd', 8, 'Odd']

In [106]:
# Exercise III
import numpy as np

x1 = np.linspace(-3, 3, 11)
y1 = x1 ** 2

print(x1)
print(y1)

[-3.  -2.4 -1.8 -1.2 -0.6  0.   0.6  1.2  1.8  2.4  3. ]
[9.   5.76 3.24 1.44 0.36 0.   0.36 1.44 3.24 5.76 9.  ]


In [109]:
x2 = [i / (5/3) for i in range(-5, 6)]   # the 5/3 part is the scaling factor
# -5 to 6 is for the 11 numbers in between
y2 = [i**2 for i in x2]
y2

[9.0,
 5.76,
 3.2399999999999993,
 1.44,
 0.36,
 0.0,
 0.36,
 1.44,
 3.2399999999999993,
 5.76,
 9.0]