In [57]:
import numpy as np

In [ ]:
lst = [10, 20, 30]

np.mean(lst)

20.0

In [ ]:
np.linspace(1, 8, 20)
# 2o numbers linearly spaced between 1 and 8

array([1.        , 1.36842105, 1.73684211, 2.10526316, 2.47368421,
       2.84210526, 3.21052632, 3.57894737, 3.94736842, 4.31578947,
       4.68421053, 5.05263158, 5.42105263, 5.78947368, 6.15789474,
       6.52631579, 6.89473684, 7.26315789, 7.63157895, 8.        ])

In [ ]:
number = [1, 1, 2, 5, 9, 10]
numbernp = np.array(number)
type(number)
type(numbernp)

print(number)
print(numbernp)

[1, 1, 2, 5, 9, 10]
[ 1  1  2  5  9 10]


In [ ]:
numbernp.min()
numbernp.max()

10

In [ ]:
n = [4, 6, 7, 3, 4, 10, 23]

n = np.sort(n)
type(n)
print(n)

[ 3  4  4  6  7 10 23]


### Pandas

In [ ]:
import pandas as pd

In [ ]:
# create some random data
var1 = np.random.randn(100)*5 + 20
var2 = np.random.randn(100) > 0

labels = ['Temp. (C)', 'Ice cream eaten']

# create a dictionary
D = {labels[0]:var1, labels[1]:var2}
D

# import the dictionary into a pandas data frame

df = pd.DataFrame(data=D)
df.head()

Temp. (C)  Ice cream eaten
0  29.410107            False
1  27.411082            False
2  10.659240            False
3  19.926278             True
4  18.154639            False

In [ ]:
df.count()

Temp. (C)          100
Ice cream eaten    100
dtype: int64

In [ ]:
df.mean()

Temp. (C)          20.395954
Ice cream eaten     0.490000
dtype: float64

In [ ]:
# exercise: create a pandas data frame with three variables:
# 1) integers from 0 to 10 
# 2) their square
# 3) their log

var1 = np.linspace(0, 10, 11)
var2 = var1**2
var3 = np.log(var1)

labelz = ["numbers", "square", "log"]

D = {labelz[1]:var2, labelz[2]:var3}

df = pd.DataFrame(data=D)
df

/tmp/ipykernel_21278/2724619109.py:8: RuntimeWarning: divide by zero encountered in log
  var3 = np.log(var1)


square       log
0      0.0      -inf
1      1.0  0.000000
2      4.0  0.693147
3      9.0  1.098612
4     16.0  1.386294
5     25.0  1.609438
6     36.0  1.791759
7     49.0  1.945910
8     64.0  2.079442
9     81.0  2.197225
10   100.0  2.302585

In [ ]:
nums = np.array(range(11))
D = {'square': nums**2, 'log': np.log(nums)}

df = pd.DataFrame(data=D)
df

/tmp/ipykernel_21278/2365593525.py:2: RuntimeWarning: divide by zero encountered in log
  D = {'square': nums**2, 'log': np.log(nums)}


square       log
0        0      -inf
1        1  0.000000
2        4  0.693147
3        9  1.098612
4       16  1.386294
5       25  1.609438
6       36  1.791759
7       49  1.945910
8       64  2.079442
9       81  2.197225
10     100  2.302585

### Creating Functions

In [ ]:
def awesomeFunction():
    print(1+1)

In [ ]:
awesomeFunction()

2


In [ ]:
# lambda functions

littlefun = lambda x : x**2 - 1

littlefun(10)

99

In [58]:
# Exercise! Create a function that computes a factorial of an integer
# 5! = 5*4*3*2*1
# compare with the math module
import math

def factorial_f(num):
    while num >= 0:
        num = num*(num-1)
        
    fac = num
    return fac

factorial_f(5)
